# Generated by Django 2.2.5 on 2019-11-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='courses/%Y/%m/%d/'),
        ),
    ]
