# Generated by Django 2.2.5 on 2019-11-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20191110_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='courses/attachments/%Y/%m/%d/'),
        ),
    ]
